# Uncomment this line to define a global platform for your project
 platform :ios, ‘9.0’
# Uncomment this line if you're using Swift
use_frameworks!

target 'CODE' do
pod 'Google/SignIn'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit' 
pod 'Alamofire', '~> 3.5'
pod 'CVCalendar', '~> 1.2.9'
pod 'RealmSwift'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'BWWalkthrough'
pod 'Firebase’
pod 'Firebase/Messaging’
pod 'PKHUD', '~> 3.0'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'  ## or '3.0'
        end
    end
end
end

target 'CODETests' do

end

target 'CODEUITests' do

end

